// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_Screen1_update_analog_read(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_s1PanelFundo;
lv_obj_t * ui_s1PanelTopo;
lv_obj_t * ui_s1Titulo;
lv_obj_t * ui_s1LeituraUmid;
void ui_event_setPointUmidadeAlta(lv_event_t * e);
lv_obj_t * ui_setPointUmidadeAlta;
lv_obj_t * ui_labelUmidadeAlta;
void ui_event_Keyboard2(lv_event_t * e);
lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_setPointUmidadeAlta(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_FOCUSED) {
        // Mostra o teclado quando o campo de texto ganha foco
        lv_obj_clear_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);
        lv_keyboard_set_textarea(ui_Keyboard2, ui_setPointUmidadeAlta);
    }

    if (event_code == LV_EVENT_DEFOCUSED) {
        // Esconde o teclado quando o campo de texto perde o foco
        lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);
    }
}


void ui_event_Keyboard2(lv_event_t * e)
{
    
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        defineSPUmidadeAlta(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
