// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_Screen1_update_analog_read(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_s1PanelFundo;
extern lv_obj_t * ui_s1PanelTopo;
extern lv_obj_t * ui_s1Titulo;
extern lv_obj_t * ui_s1LeituraUmid;
void ui_event_setPointUmidadeAlta(lv_event_t * e);
extern lv_obj_t * ui_setPointUmidadeAlta;
extern lv_obj_t * ui_labelUmidadeAlta;
void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
